# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST https://localhost:7088/api/v1/submit
Content-Type: application/json

{
  "userId": "aec74d40-83da-465d-aa09-0aef4e374435",
  "url": "https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/overview",
  "tags": [
    ".net",
    ".net 9",
    "asp.net",
    "c#",
    "c# 13"
  ]
}

###

POST https://localhost:7088/api/v1/submits
Content-Type: application/json

{
  "userId": "3b45ef37-6408-488f-bfe1-e1126e000816",
 "urls": [
    "https://www.allrecipes.com/recipe/47844/grilled-mexican-steak/",
    "https://www.bbcgoodfood.com/recipes/stickiest-ever-bbq-ribs-chive-dip",
    "https://www.feastingathome.com/vegetarian-enchiladas/",
    "https://www.bbcgoodfood.com/recipes/sticky-chicken",
    "https://cooking.nytimes.com/recipes/1026486-pozole-verde",
    "https://www.allrecipes.com/french-onion-burgers-recipe-8729996",
    "https://www.bbcgoodfood.com/recipes/rum-glazed-grilled-pineapple-with-lime-creme-fraiche",
    "https://learn.microsoft.com/en-us/dotnet/aspire/get-started/build-aspire-apps-with-nodejs",
    "https://cooking.nytimes.com/recipes/1025127-roasted-cauliflower-and-garlic-soup",
    "https://cooking.nytimes.com/recipes/1023342-grilled-turkey-burgers",
    "https://theathletic.com/4020053/2022/12/20/lloyd-donovan-mitchell-cavs-jazz-blockbuster-trade/",
    "https://www.sciencealert.com/a-new-quantum-paradox-throws-the-foundations-of-observed-reality-into-question/amp",
    "https://www.bbcgoodfood.com/recipes/dairy-free-slaw",
    "https://www.feastingathome.com/vegetable-lasagna/",
    "https://www.delish.com/cooking/recipe-ideas/a63187724/mediterranean-white-beans-and-greens-recipe/",
    "https://www.cnbc.com/2025/05/14/why-the-wealthy-cant-find-enough-people-to-manage-their-money.html",
    "https://www.delish.com/cooking/recipe-ideas/a60204284/grilled-persian-chicken-recipe/",
    "https://www.quantamagazine.org/the-spooky-quantum-phenomenon-youve-never-heard-of-20220622/",
    "https://thewalrus.ca/canadas-casinos/",
    "http://eatdrinkpaleo.com.au/mexican-tuna-steak-recipe-with-sweet-red-peppers-avocado/",
    "https://themodernproper.com/walnut-and-lentil-bolognese",
    "https://www.delish.com/cooking/recipe-ideas/recipes/a43681/pesto-shrimp-skewers-recipe/",
    "https://www.noemamag.com/the-danger-of-superhuman-ai-is-not-what-you-think/",
    "https://www.bbcgoodfood.com/recipes/spatchcock-piri-piri-chicken",
    "https://www.bbcgoodfood.com/recipes/barbecue-sauce",
    "https://www.delish.com/cooking/recipe-ideas/a27155665/greek-orzo-pasta-salad-recipe/",
    "https://cookieandkate.com/crispy-falafel-recipe/",
    "https://www.ourlifetastesgood.com/2017/03/asian-pork-meatballs-coconut-rice.html",
    "https://philmaffetone.com/recipes/",
    "https://www.foodandwine.com/recipes/slow-cooker-burnt-honey-barbecue-chicken",
    "https://www.bbcgoodfood.com/recipes/spiced-halloumi-pineapple-burger-zingy-slaw",
    "https://www.bbcgoodfood.com/recipes/air-fryer-corn-on-the-cob",
    "https://www.delish.com/cooking/recipe-ideas/a60031183/grilled-zucchini-with-ricotta-and-walnuts-recipe/",
    "https://jstutorial.medium.com/the-complete-guide-to-es10-features-5fd0feb9513a",
    "https://www.huffpost.com/entry/how-to-fall-back-asleep_l_680a76f0e4b0d1cc4a5a9666",
    "https://studio.ottomator.ai/",
    "https://www.allrecipes.com/recipe/12775/spicy-grilled-shrimp/",
    "https://www.allrecipes.com/recipe/231174/easy-chicken-fajita-marinade/",
    "https://www.consumerreports.org/health/insect-repellent/how-safe-is-deet-insect-repellent-safety-a4952100929/",
    "https://www.essence.com/culture/5-best-ways-to-prepare-for-your-hbcu-homecoming-trip/",
    "https://cooking.nytimes.com/recipes/1025023-weeknight-spinach-and-ricotta-lasagna",
    "https://www.feastingathome.com/15-minute-pad-thai/",
    "https://www.loveandlemons.com/vegetarian-stuffed-peppers/",
    "https://www.delish.com/cooking/recipe-ideas/a42399256/spicy-coconut-grilled-chicken-recipe/",
    "https://www.cntraveler.com/story/a-guide-to-barbecue-around-the-world",
    "https://www.awwwards.com/build-a-simple-javascript-app-the-mvc-way.html",
    "https://www.delish.com/cooking/recipe-ideas/a63349745/sweet-and-sour-tofu-recipe/",
    "https://themodernproper.com/vegan-roasted-sweet-potato-salad",
    "https://www.delish.com/cooking/recipe-ideas/a43555749/grilled-steak-salad-recipe/",
    "https://cooking.nytimes.com/recipes/1025356-slow-cooker-bbq-pulled-chicken",
    "https://www.delish.com/cooking/recipe-ideas/a21097616/grilled-chicken-salad-recipe/",
    "https://www.afar.com/magazine/what-to-do-if-you-lost-an-item-on-a-flight-or-at-the-airport",
    "https://www.self.com/gallery/overripe-banana-recipes",
    "https://cooking.nytimes.com/recipes/1025437-adobo-seasoning",
    "https://www.livescience.com/quantum-tunneling-observed-and-measured.html",
    "https://www.thestar.com/life/food_wine/recipes/2018/05/10/these-sweet-and-spicy-bbq-wings-were-made-to-try.html",
    "https://www.bbcgoodfood.com/recipes/collection/healthy-soup-recipes",
    "https://thelocal.to/toronto-encampment-analysis/",
    "https://www.feastingathome.com/instant-pot-butternut-risotto-with-leeks/",
    "https://www.loveandlemons.com/soup-recipes/",
    "https://cyclingtips.com/2020/06/santa-cruz-gets-into-the-road-wheelset-game-with-new-reserve-carbon-models/",
    "https://cooking.nytimes.com/recipes/1023445-dal-adas-spicy-red-lentil-tamarind-soup",
    "https://cookieandkate.com/best-lentil-soup-recipe/",
    "https://theathletic.com/4116211/2023/01/30/nba-power-rankings-week-16/",
    "https://www.allrecipes.com/recipe/265380/arrachera-mexican-skirt-steak-for-tacos/  ",
    "https://theathletic.com/3960261/2022/12/02/nhl-power-rankings-maple-leafs/",
    "https://www.delish.com/cooking/recipe-ideas/a40729912/tex-mex-chicken-fajita-foil-packets-recipe/",
    "https://www.self.com/story/resistance-bands-strength-training",
    "https://www.delish.com/cooking/recipe-ideas/a60179316/best-grilled-stuffed-peppers-recipe/",
    "https://www.allrecipes.com/recipe/60111/margarita-grilled-shrimp/",
    "https://www.bbcgoodfood.com/recipes/chicken-gyros",
    "https://www.delish.com/cooking/recipe-ideas/a63667672/spinach-artichoke-white-bean-skillet-recipe/",
    "https://www.loveandlemons.com/buddha-bowl-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/a60759791/queso-mac-and-cheese-recipe/",
    "https://www.ft.com/content/e8d14ee2-fe7f-48d5-8ac2-266582735301",
    "https://pinchofyum.com/creamy-garlic-herb-mushroom-spaghetti",
    "https://www.feastingathome.com/eggplant-lasagna/",
    "https://www.allrecipes.com/recipe/234270/grilled-pork-tacos-al-pastor/",
    "https://www.allrecipes.com/recipe/214827/mexican-steak-torta/",
    "https://pudding.cool/2024/09/lineup/",
    "https://cookieandkate.com/classic-minestrone-soup-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/a40155448/grilled-brie-with-wine-recipe/",
    "https://www.loveandlemons.com/falafel/",
    "https://www.delish.com/cooking/recipe-ideas/a60198540/bbq-pulled-mushrooms-recipe/",
    "https://www.loveandlemons.com/soup-recipes/",
    "https://www.delish.com/cooking/recipe-ideas/a64478995/cheesy-asparagus-orzotto-recipe/",
    "https://nautil.us/winning-by-a-hair-341059/",
    "https://www.sitepoint.com/single-page-app-without-framework/",
    "https://www.curiouscuisiniere.com/caribbean-red-beans-and-rice/",
    "https://cooking.nytimes.com/recipes/1025387-kabab-koobideh",
    "https://www.delish.com/cooking/recipe-ideas/a36816966/bbq-tempeh-sandwiches-recipe/",
    "https://cooking.nytimes.com/recipes/1024219-grilled-chicken-legs",
    "https://www.delish.com/cooking/recipe-ideas/a63249207/cheesy-broccoli-cheddar-chickpea-skillet-recipe/",
    "https://cookieandkate.com/vegetarian-enchilada-casserole-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/a43932602/elote-recipe/",
    "https://www.bbcgoodfood.com/recipes/pineapple-salsa",
    "https://cooking.nytimes.com/recipes/1018156-simplest-grilled-shrimp",
    "https://www.delish.com/cooking/recipe-ideas/a39614071/grilled-carrots-recipe/",
    "https://globalnews.ca/news/10858448/trump-win-canada-election-trudeau/",
    "https://www.allrecipes.com/smoked-pork-chops-with-sauerkraut-recipe-8732958",
    "https://techcommunity.microsoft.com/blog/educatordeveloperblog/building-ai-agent-applications-series---using-autogen-to-build-your-ai-agents/4052280",
    "https://www.theverge.com/2024/10/10/24266333/ai-agents-assistants-openai-google-deepmind-bots",
    "https://medium.com/the-andela-way/how-to-successfully-lead-a-software-development-team-6b9a6ffcf760",
    "https://www.delish.com/cooking/a45877598/indian-butter-chickpeas-recipe/",
    "https://www.allrecipes.com/smoked-bologna-recipe-8786384",
    "https://www.delish.com/cooking/recipe-ideas/a63411814/marry-me-tofu-recipe/",
    "https://cooking.nytimes.com/recipes/1024533-grilled-harissa-shrimp",
    "https://www.feastingathome.com/butternut-lasagna-with-mushrooms-and-sage/",
    "https://themodernproper.com/butternut-squash-soup",
    "https://www.ricardocuisine.com/en/recipes/5774-maple-glazed-chicken-drumsticks",
    "https://www.washingtonpost.com/wellness/2025/04/20/healthy-aging-exercise-benefits-jeannie-rice/",
    "https://www.texasmonthly.com/recipe/convenience-west-carrot-dip/",
    "https://www.ricardocuisine.com/en/recipes/4726-barbecued-ribs-the-best",
    "https://lifehacker.com/science/common-recycling-mistakes",
    "https://www.delish.com/cooking/recipe-ideas/a60129633/grilled-fish-sandwich-with-slaw-and-tzatziki-recipe/",
    "https://cooking.nytimes.com/recipes/1025661-grilled-chicken-breasts-with-arugula-pesto",
    "https://www.feastingathome.com/vegetarian-shepherds-pie/",
    "https://www.allrecipes.com/recipe/186691/lisas-favorite-carne-asada-marinade/",
    "https://cooking.nytimes.com/recipes/1025658-curry-tomatoes-and-chickpeas-with-cucumber-yogurt",
    "https://cookieandkate.com/vegetable-fried-rice-recipe/",
    "https://www.howsweeteats.com/2020/08/chipotle-bbq-chicken/",
    "https://medium.com/@kenzic/getting-started-model-context-protocol-e0a80dddff80",
    "https://cooking.nytimes.com/recipes/1025876-creamy-sun-dried-tomato-pasta",
    "https://cooking.nytimes.com/recipes/1024054-grilled-shrimp-with-spicy-slaw",
    "https://decapcms.org/docs/intro/",
    "https://www.feastingathome.com/eggplant-parmesan/",
    "https://learn.microsoft.com/en-us/azure/architecture/microservices/ci-cd",
    "https://cooking.nytimes.com/recipes/1024441-pollo-asado",
    "https://www.delish.com/cooking/a40080591/grilled-tomatoes-recipe/",
    "https://blog.logrocket.com/web-workers-react-typescript",
    "https://www.loveandlemons.com/bibimbap-recipe/",
    "https://www.newsweek.com/2019/09/20/real-cost-blue-jeans-labor-environment-fashionopolis-book-extract-1457027.html",
    "https://www.delish.com/cooking/recipe-ideas/a46092645/sesame-tofu-and-broccoli-recipe/",
    "https://www.bbcgoodfood.com/recipes/halloumi-watermelon-bulgur-salad",
    "https://cooking.nytimes.com/recipes/1024371-paneer-chile-dry",
    "https://theathletic.com/3966303/2022/12/04/raptors-magic-observations-anunoby/",
    "https://code-boxx.com/simple-pure-javascript-calendar-events/",
    "https://www.simplyrecipes.com/recipes/jamaican_rice_and_peas/",
    "https://www.delish.com/cooking/recipe-ideas/a39977652/grilled-green-tomatoes-recipe/",
    "https://theathletic.com/3229209/2022/04/05/hes-not-done-healing-surviving-the-devastating-humboldt-broncos-crash-was-just-the-beginning/",
    "https://cooking.nytimes.com/recipes/1025451-grilled-pork-chops-with-pineapple-salsa",
    "https://economictimes.indiatimes.com/news/company/corporate-trends/over-half-of-indias-technology-media-and-telecommunications-organisations-fully-integrated-ai/articleshow/114310254.cms",
    "https://www.delish.com/cooking/recipe-ideas/a28198532/hot-dog-veggie-skewers-recipe/",
    "https://www.thekitchn.com/jerk-chicken-jamaican-rice-and-peas-recipe-256069",
    "https://www.allrecipes.com/recipe/254449/grilled-grapefruit-paloma-cocktail/",
    "https://www.red-gate.com/simple-talk/development/dotnet-development/a-practical-guide-to-dapper/",
    "https://www.delish.com/cooking/recipe-ideas/a64165859/marry-me-chickpeas-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/a46625501/grilled-teriyaki-cauliflower-steaks-recipe/",
    "https://www.loveandlemons.com/vegetarian-lasagna/",
    "https://www.delish.com/cooking/recipe-ideas/a62964331/chili-crisp-fried-tofu-recipe/",
    "https://www.chelseasmessyapron.com/chicken-tacos/",
    "https://www.thecut.com/article/how-to-flirt-bartender-tips.html",
    "https://www.theregister.com/2022/09/28/intel_chiplets_advanced_packaging/",
    "https://www.ambitiouskitchen.com/healthy-banana-recipes/",
    "https://www.vox.com/identities/2019/6/22/18700875/lgbtq-good-ally",
    "https://www.allrecipes.com/chicken-koftas-recipe-8679670",
    "https://cookieandkate.com/roasted-carrots-recipe-with-farro-chickpeas/",
    "https://cooking.nytimes.com/recipes/1021127-grilled-salmon-salad-with-lime-chiles-and-herbs",
    "https://www.delish.com/cooking/recipe-ideas/a39500269/grilled-ribs-recipe/",
    "https://www.allrecipes.com/greek-style-grilled-lamb-chops-recipe-8680071",
    "https://www.bbcgoodfood.com/recipes/pulled-pork",
    "https://www.foodandwine.com/recipes/burnt-ends-with-bourbon-sauce",
    "https://www.delish.com/cooking/recipe-ideas/a38952025/tofu-lettuce-wraps-recipe/",
    "https://www.thestar.com/life/food_wine/2018/08/19/pasta-with-sausage-and-zucchini-spirals.html",
    "https://www.ricardocuisine.com/en/recipes/5076-chicken-skewers-with-hoisin-sauce",
    "https://www.delish.com/cooking/recipe-ideas/a46620809/grilled-tomato-feta-pizzettes-recipe/",
    "https://www.foodandwine.com/rib-tips-andouille-sausage-amarillo-barbecue-sauce-7546777",
    "https://jamstack.org/headless-cms/agility-cms/",
    "https://www.bicycling.com/health-nutrition/a20039186/mmm-tasty-a-cyclist-s-guide-to-perfect-barbecue/",
    "https://www.delish.com/cooking/recipe-ideas/a54231/easy-homemade-falafel-recipe/",
    "https://www.sbnation.com/wnba/2019/5/23/18636639/wnba-male-practice-squads",
    "https://endjin.com/blog/2022/01/raising-coding-standard-dotnet-analyzers",
    "https://cooking.nytimes.com/recipes/1024554-steak-seasoning",
    "https://bigthink.com/starts-with-a-bang/james-webb-space-telescope-changed-cosmology/",
    "https://www.ricardocuisine.com/en/recipes/8407-grilled-tomahawk-steak",
    "https://www.delish.com/cooking/a45876266/crispy-sheet-pan-black-bean-tacos-recipe/",
    "https://themodernproper.com/spring-salad-with-barley-and-lemon-chive-vinaigrette",
    "https://www.wallpaper.com/entertaining/hot-drink-recipes",
    "https://www.suse.com/lp/kubernetes-for-dummies/",
    "https://www.bbcgoodfood.com/recipes/korean-chilli-sesame-honey-chicken",
    "https://www.loveandlemons.com/frittata-recipe/",
    "https://cookieandkate.com/lentil-baked-ziti-recipe/",
    "https://heygrillhey.com/smoked-mac-and-cheese",
    "https://themodernproper.com/curried-cauliflower-quinoa-salad",
    "https://cooking.nytimes.com/recipes/1025017-lemony-pearl-barley-soup",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
    "https://www.feastingathome.com/tandoori-glory-bowl/",
    "https://www.milanjovanovic.tech/blog/build-ci-cd-pipeline-with-github-actions-and-dotnet",
    "https://arstechnica.com/gaming/2022/04/tandis-review-the-ultimate-geometry-based-puzzle-game/",
    "https://www.delish.com/cooking/recipe-ideas/a60031183/grilled-zucchini-with-ricotta-and-walnuts-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/a46625501/grilled-teriyaki-cauliflower-steaks-recipe/",
    "https://www.bonappetit.com/story/social-omnivore-vegetarian-meat",
    "https://www.softwaretestinghelp.com/unit-testing-tools/",
    "https://www.ricardocuisine.com/en/recipes/720-garlic-flap-steaks",
    "https://www.deliciousmagazine.co.uk/vegetarian-comfort-food-recipes/",
    "https://cooking.nytimes.com/recipes/1020827-jamie-olivers-vegetarian-black-bean-burgers",
    "https://www.allrecipes.com/recipe/254279/chef-johns-yucatan-style-grilled-pork/",
    "https://www.allrecipes.com/grilled-halibut-foil-packs-recipe-8705119",
    "https://www.foodnetwork.ca/baking/photos/15-ingenious-ways-to-use-overripe-bananas",
    "https://themodernproper.com/vegetable-soup",
    "https://www.geniuskitchen.com/recipe/super-simple-grilled-corn-on-the-cob-no-foil-no-husks-245576",
    "https://theathletic.com/4021985/2022/12/20/chicago-bulls-zach-lavine-demar-derozan/",
    "https://www.allrecipes.com/grilled-salmon-with-chimichurri-recipe-8699671",
    "https://cookieandkate.com/black-bean-sweet-potato-enchiladas/",
    "https://www.ricardocuisine.com/en/recipes/7302-portuguese-style-grilled-chicken-the-best",
    "https://themodernproper.com/creamy-goat-cheese-polenta-with-ratatouille",
    "https://www.bbcgoodfood.com/recipes/classic-homemade-coleslaw",
    "https://cooking.nytimes.com/recipes/1024915-seared-bone-in-rib-eye-steaks",
    "https://rainbowplantlife.com/vegan-bbq-recipes/",
    "https://cooking.nytimes.com/recipes/1019221-vegetarian-shepherds-pie",
    "https://www.delish.com/cooking/recipe-ideas/a60179769/grilled-peach-salad-recipe/",
    "https://www.loveandlemons.com/cauliflower-tacos/",
    "https://www.foodandwine.com/rum-guava-glazed-spareribs-7550638",
    "https://thehustle.co/the-guy-who-quit-medical-school-to-become-an-nba-referee/",
    "https://arstechnica.com/science/2023/02/a-guide-to-not-understanding-quantum-mechanics/",
    "https://cooking.nytimes.com/recipes/1016919-grilled-or-oven-roasted-santa-maria-tri-tip",
    "https://lifehacker.com/health/how-to-choose-a-kettlebell",
    "https://themodernproper.com/vegetarian-burrito-bowl-with-avocado-crema",
    "https://www.gq-magazine.co.uk/article/marvel-cinematic-universe-decline",
    "https://cookieandkate.com/vegetable-paella-recipe/",
    "http://www.healthy-inspiration.com/13-healthy-recipes-to-use-up-overripe-bananas/",
    "https://css-tricks.com/how-do-you-structure-javascript-the-module-pattern-edition/",
    "https://cookieandkate.com/spicy-kale-and-coconut-fried-rice/",
    "https://themodernproper.com/green-curry-buddha-bowl",
    "https://www.axios.com/2024/10/21/ai-agents-microsoft-salesforce-sierra",
    "http://www.eatingwell.com/recipes/22399/mealtimes/dinner/for-two/romantic-dinners-for-two/slideshow/romantic-dinners-for-two/?recipeId=253076",
    "https://cookieandkate.com/peanut-soba-noodle-slaw-recipe/",
    "https://www.delish.com/cooking/a36138123/chipotle-tofu-pineapple-skewers-recipe/",
    "https://www.delish.com/cooking/a20866944/how-long-to-grill-burgers/",
    "https://cookieandkate.com/roasted-cauliflower-and-farro-salad-with-feta-and-avocado/",
    "https://www.nytimes.com/athletic/5640391/2024/07/16/team-usa-basketball-fiba-rules-lebron-james-joel-embiid/",
    "https://www.texasmonthly.com/food/from-barbacoa-to-barbecue/",
    "https://www.bbcgoodfood.com/recipes/vegan-kebabs-avocado-dressing",
    "https://theathletic.com/3958290/2022/12/02/nba-2022-23-biggest-surprises/",
    "https://www.bbcgoodfood.com/recipes/beef-burgers-learn-make",
    "https://cookieandkate.com/pinto-posole-recipe/",
    "https://www.theguardian.com/food/2019/aug/29/eat-much-less-meat-top-vegan-tips-from-worlds-tastiest-cuisines",
    "https://theathletic.com/3980714/2022/12/21/nba-best-performance-2022-luka-doncic/",
    "https://www.loveandlemons.com/sesame-soba-noodles/",
    "https://www.loveandlemons.com/eggplant-parmesan/",
    "https://medium.com/computed-comparisons/commonjs-vs-amd-vs-requirejs-vs-es6-modules-2e814b114a0b",
    "https://www.bbcgoodfood.com/recipes/chicken-tikka-skewers",
    "https://www.infoq.com/news/2022/07/spotify-system-model-c4/",
    "https://www.foodandwine.com/recipes/aspen-2003-smoked-brisket-with-coffee-beer-mop-sauce",
    "https://medium.com/jeremy-gottfrieds-tech-blog/a-complete-guide-to-modern-web-applications-793ae71b57ad",
    "https://cooking.nytimes.com/recipes/1025659-vegan-pesto-pasta-salad",
    "https://theathletic.com/3955753/2022/12/02/joel-embiid-france-rudy-gobert/",
    "https://www.delish.com/cooking/recipe-ideas/a46266063/cottage-cheese-alfredo-recipe/",
    "https://www.ricardocuisine.com/en/recipes/5361-salmon-burgers",
    "https://www.gqindia.com/look-good/content/6-benefits-of-cycling-and-why-you-need-to-add-it-to-your-fitness-regime",
    "https://www.loveandlemons.com/vegan-ramen/",
    "https://gulfnews.com/your-money/saving-investment/ai-is-taking-over-personal-finance-does-this-mean-a-brighter-investment-future-for-us-1.1720531004623",
    "https://www.delish.com/cooking/recipe-ideas/a60204750/grilled-cod-with-romesco-sauce-recipe/",
    "https://www.allrecipes.com/hot-honey-feta-chicken-skewers-recipe-11706551",
    "https://www.mongodb.com/docs/manual/applications/data-models/",
    "https://arstechnica.com/science/2022/04/channel-your-inner-math-geek-with-this-rich-collection-of-simple-interactive-games/",
    "https://cooking.nytimes.com/recipes/1025442-smoked-prime-rib",
    "https://www.delish.com/cooking/recipe-ideas/a60964397/grilled-zucchini-carbonara-recipe/",
    "https://www.sbnation.com/college-basketball/2024/10/12/24267777/cameron-boozer-scouting-report-duke-nba-draft-top-pick-ranking",
    "https://www.loveandlemons.com/best-veggie-burger-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/a46620809/grilled-tomato-feta-pizzettes-recipe/",
    "https://mykoreankitchen.com/how-to-eat-kimchi",
    "https://www.allrecipes.com/garlic-parmesan-chicken-skewers-recipe-8685161",
    "https://pitchfork.com/features/lists-and-guides/the-best-indie-pop-albums-of-the-90s/",
    "https://www.worldhistory.org/article/1774/ten-ancient-lgbtq-facts-you-need-to-know/",
    "https://themodernproper.com/sesame-garlic-ramen-noodles",
    "https://www.outlookindia.com/brand-studio/blogs/ai-in-gaming-revolutionizing-game-development-for-coders-and-creators",
    "https://theathletic.com/3182598/2022/03/22/american-basketball-player-maurice-creeks-incredible-escape-from-ukraine-invasion-by-russia/",
    "https://www.blogto.com/eat_drink/2021/11/dickeys-bbq-toronto/",
    "https://dev.to/platformos/monitoring-website-performance-using-lighthouse-ci-1ll",
    "https://www.ricardocuisine.com/en/recipes/608-pork-souvlaki",
    "https://www.allrecipes.com/dill-pickle-chicken-skewers-recipe-11703355",
    "https://theathletic.com/3956317/2022/12/01/draymond-green-warriors-redemption/",
    "https://www.allrecipes.com/recipe/221935/fish-tacos-ultimo/",
    "https://www.quantamagazine.org/ai-makes-strides-in-virtual-worlds-more-like-our-own-20220624/",
    "https://andscape.com/features/realities-of-wnba-stars-who-play-abroad-brionna-jones-bria-hartley-jasmine-thomas-kahleah-copper/",
    "https://www.allrecipes.com/recipe/233399/mexican-grilled-corn/",
    "https://food52.com/blog/23599-best-vegetarian-recipes-for-dinner-easy-no-meat-recipes?srsltid=AfmBOorNuGVx2uYZ334Rl2m5WsNNqRhzv3fx1M2ljbRE-FdC9rLYzRPE",
    "https://levelup.gitconnected.com/5-concepts-you-must-know-as-a-react-developer-56ef56e4a5b8",
    "https://www.vox.com/life/413043/dry-texting-phones-kids-teens-teenagers-conflict-social",
    "https://www.delish.com/cooking/recipe-ideas/recipes/a53531/hawaiian-chicken-skewers-recipe/",
    "https://www.atlassian.com/blog/devops/open-devops",
    "https://www.delish.com/cooking/recipe-ideas/a40641011/peach-balsamic-grilled-chicken-recipe/",
    "https://www.wired.com/story/labgenius-antibody-factory-machine-learning/",
    "https://www.cnbc.com/2024/10/24/generative-ai-is-taking-over-the-onboarding-of-new-employees.html",
    "https://themodernproper.com/instant-pot-mac-and-cheese",
    "https://cooking.nytimes.com/recipes/1023164-smashed-cabbage-and-mushroom-veggie-burgers",
    "https://thetyee.ca/Culture/2024/11/01/What-Canadian-Horror-Tells-Us-Deepest-Fears/",
    "https://cookieandkate.com/thai-red-curry-recipe/",
    "https://themodernproper.com/perfect-grilled-cheese",
    "https://theathletic.com/3950004/2022/12/02/kia-nurse-canada-wnba/",
    "https://devblogs.microsoft.com/semantic-kernel/guest-blog-building-multi-agent-systems-with-multi-models-in-semantic-kernel-part-1/",
    "https://medium.com/@kenzic/getting-started-build-a-model-context-protocol-server-9d0362363435",
    "https://www.theatlantic.com/ideas/archive/2022/05/supreme-court-roe-handmaids-tale-abortion-margaret-atwood/629833/",
    "https://www.bbcgoodfood.com/recipes/classic-potato-salad",
    "https://www.delish.com/cooking/recipe-ideas/a40397943/honey-lime-grilled-corn-recipe/",
    "https://www.onceuponachef.com/recipes/grilled-shrimp-tacos-with-avocado-salsa.html",
    "https://www.quantamagazine.org/quantum-algorithms-conquer-a-new-kind-of-problem-20220711/",
    "https://www.allrecipes.com/recipe/269262/baja-grilled-chicken-tacos/",
    "https://www.delish.com/cooking/recipe-ideas/a46819332/grilled-portobello-tacos-recipe/",
    "https://www.independent.co.uk/extras/indybest/food-drink/best-hot-sauce-sriracha-uk-brands-b1799734.html",
    "https://www.cloudpipes.com/integrations/lighthouse/teamcity",
    "https://www.allrecipes.com/recipe/257951/oven-baked-chicken-fajitas/",
    "https://cookieandkate.com/roasted-cauliflower-and-lentil-tacos/",
    "https://cookieandkate.com/spaghetti-squash-burrito-bowl-recipe/",
    "https://themodernproper.com/shaved-brussels-sprout-salad-with-creamy-maple-dressing",
    "https://arstechnica.com/features/2021/10/securing-your-digital-life-part-1/",
    "https://www.ricardocuisine.com/en/recipes/4145-sesame-and-honey-marinated-tofu-skewers",
    "https://www.inverse.com/gaming/katamari-damacy-anniversary-20-years",
    "https://theathletic.com/3954089/2022/12/07/luis-scola-varese-basketball/",
    "https://www.delish.com/cooking/recipe-ideas/a39975008/slutty-vegan-one-night-stand-burger-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/recipes/a47334/grilled-romaine-caesar-wedge-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/a43365832/jerk-shrimp-and-pineapple-bowls-recipe/",
    "https://cooking.nytimes.com/recipes/1026610-porcini-ragu",
    "https://www.milanjovanovic.tech/blog/the-right-way-to-use-httpclient-in-dotnet",
    "https://cookieandkate.com/best-vegetable-lasagna-recipe/",
    "https://www.loveandlemons.com/cauliflower-fried-rice/",
    "https://lifehacker.com/these-sauces-are-mother-you-listen-to-them-1850219813",
    "https://www.techwalla.com/articles/how-to-outline-something-quickly-in-paintnet",
    "https://slate.com/technology/2022/05/alex-epstein-fossil-future-climate-change-argument.html?via=rss",
    "https://www.w3schools.io/javascript/es10-features/",
    "https://cooking.nytimes.com/recipes/1022335-grilled-chicken-with-parsley-olive-sauce",
    "https://www.ricardocuisine.com/en/recipes/785-beer-can-chicken",
    "https://www.cnn.com/2022/06/04/tech/blue-origin-launch-space-for-humanity-scn/index.html",
    "https://learn.microsoft.com/en-us/azure/architecture/example-scenario/apps/ecommerce-scenario",
    "https://theathletic.com/4020157/2022/12/20/damian-lillard-passes-clyde-drexler-blazers-scoring-record/",
    "https://theathletic.com/3966174/2022/12/04/jordan-poole-warriors-nba/",
    "https://jennifermeyering.com/pizza-muffins",
    "https://cookieandkate.com/epic-vegetarian-tacos-recipe/",
    "https://longreads.com/2022/10/27/letting-go-of-the-90s/",
    "https://www.insidehook.com/article/food-drink-chicago/steak-dinner-home-recipe-michelin-starred-chef",
    "https://www.bbcgoodfood.com/recipes/courgette-jalapeno-feta-nachos",
    "https://theathletic.com/3343111/2022/06/01/magic-johnson-rookie-center/",
    "https://www.thestar.com/life/food_wine/2018/07/31/a-backyard-barbecue-mash-up.html",
    "https://github.com/neo4j-examples/movies-javascript-bolt/tree/main/src",
    "https://www.foodandwine.com/recipes/pork-belly-burnt-ends-with-barbecue-sauce",
    "https://microsoft.github.io/autogen/dotnet/dev/core/index.html",
    "https://www.texasmonthly.com/food/from-barbacoa-to-barbecue/",
    "https://www.delish.com/cooking/recipe-ideas/a36561765/grilled-beer-brats-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/a46697253/steak-kebab-bowls-recipe/",
    "https://themodernproper.com/roasted-cauliflower-and-hummus-bowl",
    "https://theathletic.com/3959161/2022/12/02/jalen-brunson-knicks-mavericks-preview/",
    "https://engineering.atspotify.com/2023/04/spotifys-shift-to-a-fleet-first-mindset-part-1/",
    "https://www.eatingwell.com/recipes/18042/soup/",
    "https://theathletic.com/3900191/2022/11/17/nba-coaches-hot-seat-firings/?source=twitterpcads&ad_id=37084834",
    "https://www.delish.com/cooking/recipe-ideas/a36790969/vegan-chili-dogs-recipes/",
    "https://thewalrus.ca/its-like-a-cult-breaking-free-from-the-far-right/",
    "https://cooking.nytimes.com/recipes/1025547-carrot-and-orange-salad",
    "https://cooking.nytimes.com/recipes/1013116-homemade-bbq-sauce",
    "https://arstechnica.com/science/2022/12/fifty-years-later-remastered-images-reveal-apollo-17-in-stunning-clarity/",
    "https://www.delish.com/cooking/recipe-ideas/a62964330/baked-feta-chickpeas-recipe/",
    "https://www.cnet.com/home/kitchen-and-household/did-a-poultry-professor-at-cornell-invent-bbq-chicken-heres-how-to-make-the-iconic-bird/",
    "https://cooking.nytimes.com/recipes/1023284-chicago-style-hot-dogs",
    "https://www.milanjovanovic.tech/",
    "https://cooking.nytimes.com/recipes/1025265-mushroom-queso-fundido",
    "https://www.delish.com/cooking/recipe-ideas/a60255566/grilled-shrimp-piccata-skewers-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/a36621814/gnocchi-foil-packets-recipe/",
    "https://www.youtube.com/watch?v=IGVRVO7KTss&t=1s",
    "https://www.delish.com/cooking/recipe-ideas/a63835870/miso-mushroom-crispy-rice-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/a40433446/grilled-halloumi-recipe/",
    "https://www.delish.com/cooking/recipe-ideas/a27544267/grilled-cabbage-steaks-recipe/",
    "https://www.delish.com/cooking/menus/a44789804/butterflied-grilled-chicken-drumsticks-recipe/",
    "https://www.thestar.com/life/food_wine/recipes/2018/05/10/these-sweet-and-spicy-bbq-wings-were-made-to-try.html",
    "https://www.technologyreview.com/2019/01/29/66141/what-is-quantum-computing/",
    "https://www.popularmechanics.com/science/a40898392/quantum-physics-consciousness/",
    "https://www.bbcgoodfood.com/recipes/halloumi-burgers",
    "https://www.theglowingfridge.com/spicy-black-bean-burgers/",
    "https://www.bbcgoodfood.com/recipes/buttery-baked-corn-cob",
    "https://arstechnica.com/information-technology/2023/02/ars-archivum-top-cloud-backup-services-worth-your-money/",
    "https://cooking.nytimes.com/recipes/1025167-one-pot-tofu-and-broccoli-rice",
    "https://www.news18.com/sports/nba-working-to-bar-active-players-from-partaking-in-sports-betting-9091837.html",
    "https://www.nytimes.com/2019/02/08/sports/hockey/-goalie-ringer-.html",
    "https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs",
    "https://www.thekitchn.com/recipe-mushroom-and-garlic-spaghetti-dinner-243627",
    "https://css-tricks.com/css-style-guides/",
    "https://www.delish.com/cooking/recipe-ideas/a46819332/grilled-portobello-tacos-recipe/",
    "https://www.feastingathome.com/lentil-bolognese/",
    "https://www.delish.com/cooking/recipe-ideas/a39963858/grilled-tofu-recipe/",
    "https://www.bdo.com/digital/insights/application-development/5-tips-organize-javascript-without-framework",
    "https://www.delish.com/cooking/recipe-ideas/a60669882/grilled-plum-and-pancetta-panzanella-salad-recipe/",
    "https://www.seriouseats.com/recipes/2012/06/grilled-garlic-lime-shrimp-recipe.html",
    "https://lifehacker.com/the-best-way-to-add-protein-to-your-next-bowl-1849391111",
    "https://www.bbc.com/future/article/20220601-what-your-favourite-colour-says-about-you",
    "https://www.christianfindlay.com/blog/code-rules",
    "https://www.delish.com/cooking/recipe-ideas/a63184853/creamy-lemon-garlic-butter-beans-recipe/",
    "https://www.theatlantic.com/ideas/archive/2025/05/young-people-global-unhappiness/682632/",
    "https://themodernproper.com/curried-pumpkin-coconut-soup",
    "https://cooking.nytimes.com/recipes/1024586-grilled-steak-with-tomatoes-basil-and-cheddar",
    "https://www.delish.com/cooking/recipe-ideas/a21755976/surf-n-turf-foil-packs-recipe/",
    "https://www.loveandlemons.com/pasta-primavera/",
    "https://www.mongodb.com/events/mongodb-local/toronto#mdb-modal-agenda",
    "https://cooking.nytimes.com/recipes/1024190-grilled-pork-chops",
    "https://www.mashed.com/1614664/cheesy-bbq-beef-casserole-recipe/"
  ]
}

###