# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST https://localhost:7088/api/v1/submit
Content-Type: application/json

{
  "userId": "aec74d40-83da-465d-aa09-0aef4e374435",
  "url": "https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-9/overview",
  "tags": [
    ".net",
    ".net 9",
    "asp.net",
    "c#",
    "c# 13"
  ]
}

###

POST https://localhost:7088/api/v1/submits
Content-Type: application/json

{
  "userId": "aec74d40-83da-465d-aa09-0aef4e374435",
 "urls": [
    "https://www.sciencealert.com/a-new-quantum-paradox-throws-the-foundations-of-observed-reality-into-question/amp",
    "https://cyclingtips.com/2020/06/santa-cruz-gets-into-the-road-wheelset-game-with-new-reserve-carbon-models/",
    "https://www.blogto.com/eat_drink/2021/11/dickeys-bbq-toronto/",
    "https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs",
    "https://engineering.atspotify.com/2023/04/spotifys-shift-to-a-fleet-first-mindset-part-1/",
    "https://learn.microsoft.com/en-us/azure/architecture/example-scenario/apps/ecommerce-scenario",
    "https://www.atlassian.com/blog/devops/open-devops",
    "https://levelup.gitconnected.com/5-concepts-you-must-know-as-a-react-developer-56ef56e4a5b8",
    "https://mykoreankitchen.com/how-to-eat-kimchi",
    "https://jennifermeyering.com/pizza-muffins",
    "https://heygrillhey.com/smoked-mac-and-cheese",
    "https://www.infoq.com/news/2022/07/spotify-system-model-c4/",
    "https://blog.logrocket.com/web-workers-react-typescript",
    "https://www.howsweeteats.com/2020/08/chipotle-bbq-chicken/",
    "https://www.youtube.com/watch?v=IGVRVO7KTss&t=1s",
  "https://www.milanjovanovic.tech/",
  "https://www.milanjovanovic.tech/blog/the-right-way-to-use-httpclient-in-dotnet",
  "https://www.milanjovanovic.tech/blog/build-ci-cd-pipeline-with-github-actions-and-dotnet",
  "https://www.red-gate.com/simple-talk/development/dotnet-development/a-practical-guide-to-dapper/",
  "https://medium.com/computed-comparisons/commonjs-vs-amd-vs-requirejs-vs-es6-modules-2e814b114a0b",
  "https://www.awwwards.com/build-a-simple-javascript-app-the-mvc-way.html",
  "https://www.w3schools.io/javascript/es10-features/",
  "https://code-boxx.com/simple-pure-javascript-calendar-events/",
  "https://www.sitepoint.com/single-page-app-without-framework/",
  "https://jstutorial.medium.com/the-complete-guide-to-es10-features-5fd0feb9513a",
  "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes",
  "https://github.com/neo4j-examples/movies-javascript-bolt/tree/main/src",
  "https://www.bdo.com/digital/insights/application-development/5-tips-organize-javascript-without-framework",
  "https://css-tricks.com/how-do-you-structure-javascript-the-module-pattern-edition/",
  "https://medium.com/jeremy-gottfrieds-tech-blog/a-complete-guide-to-modern-web-applications-793ae71b57ad",
  "https://www.suse.com/lp/kubernetes-for-dummies/",
  "https://www.cloudpipes.com/integrations/lighthouse/teamcity",
  "https://dev.to/platformos/monitoring-website-performance-using-lighthouse-ci-1ll",
  "https://www.softwaretestinghelp.com/unit-testing-tools/",
  "https://css-tricks.com/css-style-guides/",
  "https://arstechnica.com/features/2021/10/securing-your-digital-life-part-1/",
  "https://www.insidehook.com/article/food-drink-chicago/steak-dinner-home-recipe-michelin-starred-chef",
  "https://theathletic.com/3182598/2022/03/22/american-basketball-player-maurice-creeks-incredible-escape-from-ukraine-invasion-by-russia/",
  "https://theathletic.com/3229209/2022/04/05/hes-not-done-healing-surviving-the-devastating-humboldt-broncos-crash-was-just-the-beginning/",
  "https://arstechnica.com/science/2022/04/channel-your-inner-math-geek-with-this-rich-collection-of-simple-interactive-games/",
  "https://thehustle.co/the-guy-who-quit-medical-school-to-become-an-nba-referee/",
  "https://www.theregister.com/2022/09/28/intel_chiplets_advanced_packaging/",
  "https://arstechnica.com/gaming/2022/04/tandis-review-the-ultimate-geometry-based-puzzle-game/",
  "https://www.theatlantic.com/ideas/archive/2022/05/supreme-court-roe-handmaids-tale-abortion-margaret-atwood/629833/",
  "https://slate.com/technology/2022/05/alex-epstein-fossil-future-climate-change-argument.html?via=rss",
  "https://theathletic.com/3343111/2022/06/01/magic-johnson-rookie-center/",
  "https://jamstack.org/headless-cms/agility-cms/",
  "https://www.mongodb.com/docs/manual/applications/data-models/",
  "https://www.techwalla.com/articles/how-to-outline-something-quickly-in-paintnet",
  "https://theathletic.com/3966174/2022/12/04/jordan-poole-warriors-nba/",
  "https://theathletic.com/3966303/2022/12/04/raptors-magic-observations-anunoby/",
  "https://theathletic.com/3958290/2022/12/02/nba-2022-23-biggest-surprises/",
  "https://theathletic.com/3960261/2022/12/02/nhl-power-rankings-maple-leafs/",
  "https://theathletic.com/3959161/2022/12/02/jalen-brunson-knicks-mavericks-preview/",
  "https://theathletic.com/3956317/2022/12/01/draymond-green-warriors-redemption/",
  "https://theathletic.com/3955753/2022/12/02/joel-embiid-france-rudy-gobert/",
  "https://theathletic.com/3900191/2022/11/17/nba-coaches-hot-seat-firings/?source=twitterpcads&ad_id=37084834",
  "https://www.mongodb.com/events/mongodb-local/toronto#mdb-modal-agenda",
  "https://arstechnica.com/science/2022/12/fifty-years-later-remastered-images-reveal-apollo-17-in-stunning-clarity/",
  "https://theathletic.com/3954089/2022/12/07/luis-scola-varese-basketball/",
  "https://theathletic.com/3950004/2022/12/02/kia-nurse-canada-wnba/",
  "https://theathletic.com/4116211/2023/01/30/nba-power-rankings-week-16/",
  "https://theathletic.com/3980714/2022/12/21/nba-best-performance-2022-luka-doncic/",
  "https://theathletic.com/4021985/2022/12/20/chicago-bulls-zach-lavine-demar-derozan/",
  "https://theathletic.com/4020053/2022/12/20/lloyd-donovan-mitchell-cavs-jazz-blockbuster-trade/",
  "https://theathletic.com/4020157/2022/12/20/damian-lillard-passes-clyde-drexler-blazers-scoring-record/",
  "https://www.christianfindlay.com/blog/code-rules",
  "https://endjin.com/blog/2022/01/raising-coding-standard-dotnet-analyzers",
  "https://medium.com/the-andela-way/how-to-successfully-lead-a-software-development-team-6b9a6ffcf760",
  "https://learn.microsoft.com/en-us/azure/architecture/microservices/ci-cd",
  "https://arstechnica.com/information-technology/2023/02/ars-archivum-top-cloud-backup-services-worth-your-money/",
  "https://arstechnica.com/science/2023/02/a-guide-to-not-understanding-quantum-mechanics/",
  "https://www.thestar.com/life/food_wine/2018/07/31/a-backyard-barbecue-mash-up.html",
  "https://www.bicycling.com/health-nutrition/a20039186/mmm-tasty-a-cyclist-s-guide-to-perfect-barbecue/",
  "https://www.thestar.com/life/food_wine/recipes/2018/05/10/these-sweet-and-spicy-bbq-wings-were-made-to-try.html",
  "https://philmaffetone.com/recipes/",
  "http://www.eatingwell.com/recipes/22399/mealtimes/dinner/for-two/romantic-dinners-for-two/slideshow/romantic-dinners-for-two/?recipeId=253076",
  "https://www.thestar.com/life/food_wine/recipes/2018/05/10/these-sweet-and-spicy-bbq-wings-were-made-to-try.html",
  "http://eatdrinkpaleo.com.au/mexican-tuna-steak-recipe-with-sweet-red-peppers-avocado/"
  ]
}

###