import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/navigation/Header/Header';
import Link from 'next/link';

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
});

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
});

// export const metadata: Metadata = {
//    title: 'Create Next App',
//    description: 'Generated by create next app',
// };

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <div className='mb-4 mx-auto px-4'>
               <h1 className='text-3xl font-bold'>
                  <Link href='/' className='text-blue-600 hover:italic'>
                     Delisc.io
                  </Link>
               </h1>
            </div>
            <div className='mx-auto px-4'>{children}</div>
         </body>
      </html>
   );
}
