/* tslint:disable */
/* eslint-disable */
/**
 * Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinkTag } from './LinkTag';
import {
    LinkTagFromJSON,
    LinkTagFromJSONTyped,
    LinkTagToJSON,
    LinkTagToJSONTyped,
} from './LinkTag';

/**
 * 
 * @export
 * @interface Link
 */
export interface Link {
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    domain?: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Link
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Link
     */
    isFlagged?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof Link
     */
    keywords?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof Link
     */
    likesCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Link
     */
    savesCount?: number;
    /**
     * 
     * @type {Array<LinkTag>}
     * @memberof Link
     */
    tags?: Array<LinkTag>;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    submittedById?: string;
    /**
     * 
     * @type {Date}
     * @memberof Link
     */
    dateCreated?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Link
     */
    dateUpdated?: Date;
}

/**
 * Check if a given object implements the Link interface.
 */
export function instanceOfLink(value: object): value is Link {
    return true;
}

export function LinkFromJSON(json: any): Link {
    return LinkFromJSONTyped(json, false);
}

export function LinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Link {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'description': json['description'] == null ? undefined : json['description'],
        'domain': json['domain'] == null ? undefined : json['domain'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'isFlagged': json['isFlagged'] == null ? undefined : json['isFlagged'],
        'keywords': json['keywords'] == null ? undefined : json['keywords'],
        'likesCount': json['likesCount'] == null ? undefined : json['likesCount'],
        'savesCount': json['savesCount'] == null ? undefined : json['savesCount'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(LinkTagFromJSON)),
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'] == null ? undefined : json['url'],
        'submittedById': json['submittedById'] == null ? undefined : json['submittedById'],
        'dateCreated': json['dateCreated'] == null ? undefined : (new Date(json['dateCreated'])),
        'dateUpdated': json['dateUpdated'] == null ? undefined : (new Date(json['dateUpdated'])),
    };
}

export function LinkToJSON(json: any): Link {
    return LinkToJSONTyped(json, false);
}

export function LinkToJSONTyped(value?: Link | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'description': value['description'],
        'domain': value['domain'],
        'imageUrl': value['imageUrl'],
        'isActive': value['isActive'],
        'isFlagged': value['isFlagged'],
        'keywords': value['keywords'],
        'likesCount': value['likesCount'],
        'savesCount': value['savesCount'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(LinkTagToJSON)),
        'title': value['title'],
        'url': value['url'],
        'submittedById': value['submittedById'],
        'dateCreated': value['dateCreated'] == null ? undefined : ((value['dateCreated']).toISOString()),
        'dateUpdated': value['dateUpdated'] == null ? undefined : ((value['dateUpdated']).toISOString()),
    };
}

