/* tslint:disable */
/* eslint-disable */
/**
 * Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LinkItem } from './LinkItem';
import {
   LinkItemFromJSON,
   LinkItemFromJSONTyped,
   LinkItemToJSON,
   LinkItemToJSONTyped,
} from './LinkItem';

/**
 *
 * @export
 * @interface PagedResultsOfLinkItem
 */
export interface PagedResultsOfLinkItem {
   /**
    *
    * @type {Array<LinkItem>}
    * @memberof PagedResultsOfLinkItem
    */
   results?: Array<LinkItem>;
   /**
    *
    * @type {number}
    * @memberof PagedResultsOfLinkItem
    */
   pageNumber?: number;
   /**
    *
    * @type {number}
    * @memberof PagedResultsOfLinkItem
    */
   pageSize?: number;
   /**
    *
    * @type {number}
    * @memberof PagedResultsOfLinkItem
    */
   totalResults?: number;
   /**
    *
    * @type {number}
    * @memberof PagedResultsOfLinkItem
    */
   totalPages?: number;
   /**
    *
    * @type {boolean}
    * @memberof PagedResultsOfLinkItem
    */
   isError?: boolean;
   /**
    *
    * @type {boolean}
    * @memberof PagedResultsOfLinkItem
    */
   isSuccess?: boolean;
   /**
    *
    * @type {string}
    * @memberof PagedResultsOfLinkItem
    */
   message?: string;
}

/**
 * Check if a given object implements the PagedResultsOfLinkItem interface.
 */
export function instanceOfPagedResultsOfLinkItem(value: object): value is PagedResultsOfLinkItem {
   return true;
}

export function PagedResultsOfLinkItemFromJSON(json: any): PagedResultsOfLinkItem {
   return PagedResultsOfLinkItemFromJSONTyped(json, false);
}

export function PagedResultsOfLinkItemFromJSONTyped(
   json: any,
   ignoreDiscriminator: boolean,
): PagedResultsOfLinkItem {
   if (json == null) {
      return json;
   }
   return {
      results:
         json['results'] == null
            ? undefined
            : (json['results'] as Array<any>).map(LinkItemFromJSON),
      pageNumber: json['pageNumber'] == null ? undefined : json['pageNumber'],
      pageSize: json['pageSize'] == null ? undefined : json['pageSize'],
      totalResults: json['totalResults'] == null ? undefined : json['totalResults'],
      totalPages: json['totalPages'] == null ? undefined : json['totalPages'],
      isError: json['isError'] == null ? undefined : json['isError'],
      isSuccess: json['isSuccess'] == null ? undefined : json['isSuccess'],
      message: json['message'] == null ? undefined : json['message'],
   };
}

export function PagedResultsOfLinkItemToJSON(json: any): PagedResultsOfLinkItem {
   return PagedResultsOfLinkItemToJSONTyped(json, false);
}

export function PagedResultsOfLinkItemToJSONTyped(
   value?: PagedResultsOfLinkItem | null,
   ignoreDiscriminator: boolean = false,
): any {
   if (value == null) {
      return value;
   }

   return {
      results:
         value['results'] == null
            ? undefined
            : (value['results'] as Array<any>).map(LinkItemToJSON),
      pageNumber: value['pageNumber'],
      pageSize: value['pageSize'],
      totalResults: value['totalResults'],
      totalPages: value['totalPages'],
      isError: value['isError'],
      isSuccess: value['isSuccess'],
      message: value['message'],
   };
}
