/* tslint:disable */
/* eslint-disable */
/**
 * Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitLinksRequest
 */
export interface SubmitLinksRequest {
    /**
     * 
     * @type {string}
     * @memberof SubmitLinksRequest
     */
    userId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SubmitLinksRequest
     */
    urls: Array<string>;
}

/**
 * Check if a given object implements the SubmitLinksRequest interface.
 */
export function instanceOfSubmitLinksRequest(value: object): value is SubmitLinksRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('urls' in value) || value['urls'] === undefined) return false;
    return true;
}

export function SubmitLinksRequestFromJSON(json: any): SubmitLinksRequest {
    return SubmitLinksRequestFromJSONTyped(json, false);
}

export function SubmitLinksRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitLinksRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'urls': json['urls'],
    };
}

export function SubmitLinksRequestToJSON(json: any): SubmitLinksRequest {
    return SubmitLinksRequestToJSONTyped(json, false);
}

export function SubmitLinksRequestToJSONTyped(value?: SubmitLinksRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'urls': value['urls'],
    };
}

