/* tslint:disable */
/* eslint-disable */
/**
 * Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitLinkResponse
 */
export interface SubmitLinkResponse {
    /**
     * 
     * @type {string}
     * @memberof SubmitLinkResponse
     */
    submissionId: string;
    /**
     * 
     * @type {string}
     * @memberof SubmitLinkResponse
     */
    url: string;
}

/**
 * Check if a given object implements the SubmitLinkResponse interface.
 */
export function instanceOfSubmitLinkResponse(value: object): value is SubmitLinkResponse {
    if (!('submissionId' in value) || value['submissionId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function SubmitLinkResponseFromJSON(json: any): SubmitLinkResponse {
    return SubmitLinkResponseFromJSONTyped(json, false);
}

export function SubmitLinkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitLinkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'submissionId': json['submissionId'],
        'url': json['url'],
    };
}

export function SubmitLinkResponseToJSON(json: any): SubmitLinkResponse {
    return SubmitLinkResponseToJSONTyped(json, false);
}

export function SubmitLinkResponseToJSONTyped(value?: SubmitLinkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'submissionId': value['submissionId'],
        'url': value['url'],
    };
}

